-- Caleb Wherry
-- 6/18/07
-- ACTIVE query for Northwind database

SELECT EMPLOYEEID, FIRSTNAME, LASTNAME
FROM EMPLOYEES
WHERE EXISTS
( SELECT * FROM ORDERS, [ORDER DETAILS], PRODUCTS, SUPPLIERS
WHERE EMPLOYEES.EMPLOYEEID = ORDERS.EMPLOYEEID
AND ORDERS.ORDERID = [ORDER DETAILS].ORDERID
AND [ORDER DETAILS].PRODUCTID =  PRODUCTS.PRODUCTID
AND PRODUCTS.SUPPLIERID = SUPPLIERS.SUPPLIERID
AND COMPANYNAME = 'TOKYO TRADERS')


