-- Caleb Wherry
-- 6/18/07
-- DISCONTINUED query for Northwind database

SELECT S.SUPPLIERID AS [ID  ], S.COMPANYNAME AS NAME, 
SUM(UNITPRICE*UNITSINSTOCK) AS [TOTAL VALUE FOR DISCONTINUED PRODUCTS]
FROM SUPPLIERS S, PRODUCTS P
WHERE S.SUPPLIERID = P.SUPPLIERID AND DISCONTINUED = 1
GROUP BY S.SUPPLIERID, S.COMPANYNAME