-- Caleb Wherry
-- 6/18/07
-- EMPLOYEES query for Northwind database

SELECT E.EMPLOYEEID AS ID, FIRSTNAME AS [FIRST NAME], LASTNAME AS [LAST NAME], 
COUNT(O.EMPLOYEEID) AS [NUMBER OF ORDERS TAKEN]
FROM EMPLOYEES E, ORDERS O
WHERE E.EMPLOYEEID = O.EMPLOYEEID
GROUP BY E.EMPLOYEEID, FIRSTNAME, LASTNAME
HAVING COUNT(O.EMPLOYEEID) > 4
ORDER BY [NUMBER OF ORDERS TAKEN]DESC