-- Caleb Wherry
-- 6/18/07
-- INDIVIDUAL_SUPPLIER query for Northwind database

SELECT P.PRODUCTID AS ID, P.PRODUCTNAME AS NAME, OD.QUANTITY, 
OD.UNITPRICE AS [UNIT PRICE], SUM(OD.QUANTITY*OD.UNITPRICE) AS [TOTAL COST]
FROM PRODUCTS P, [ORDER DETAILS] OD, ORDERS O, SUPPLIERS S
WHERE P.PRODUCTID = OD.PRODUCTID 
AND OD.ORDERID = O.ORDERID 
AND S.SUPPLIERID = P.SUPPLIERID AND S.COMPANYNAME = 'BIGFOOT BREWERIES'
GROUP BY P.PRODUCTID, P.PRODUCTNAME, OD.QUANTITY, OD.UNITPRICE


