-- Caleb Wherry
-- 6/18/07
-- SHIPPERS query for Northwind database

SELECT S.SHIPPERID AS ID, S.COMPANYNAME AS [COMPANY NAME], 
COUNT(SHIPVIA) AS [NUMBER OF ORDERS SHIPPED]
FROM SHIPPERS S, ORDERS O
WHERE S.SHIPPERID = O.SHIPVIA
GROUP BY S.SHIPPERID, S.COMPANYNAME
ORDER BY [NUMBER OF ORDERS SHIPPED] DESC